variables:
  GIT_STRATEGY: fetch
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
 - |
    apt-get update -qq &&
    apt-get install -qq build-essential curl fuse genisoimage gnupg libfuse-dev nasm pkg-config software-properties-common syslinux &&
    apt-key adv -q --batch --yes --keyserver keyserver.ubuntu.com --recv-keys AA12E97F0881517F &&
    add-apt-repository 'deb https://static.redox-os.org/toolchain/apt ./' &&
    apt-get update -qq &&
    apt-get purge -qq binutils-doc &&
    apt-get install -qq x86-64-unknown-redox-gcc &&
    curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain none

build:
   script:
     - make ci
