before_script:
 - |
    sudo apt-key adv -q --batch --yes --keyserver keyserver.ubuntu.com --recv-keys AA12E97F0881517F &&
    sudo add-apt-repository 'deb https://static.redox-os.org/toolchain/apt ./' &&
    sudo apt-get update -qq &&
    sudo apt-get purge -qq binutils-doc &&
    sudo apt-get install -qq nasm pkg-config fuse libfuse-dev genisoimage syslinux realpath x86-64-unknown-redo$
    sudo modprobe fuse &&
    sudo chmod 666 /dev/fuse &&
    sudo chown root:$USER /etc/fuse.conf &&
    curl https://sh.rustup.rs -sSf | sh

build:
   script:
     - make ci
