image: "redoxos/redox"

variables:
  GIT_STRATEGY: "pull"
  GIT_SUBMODULE_STRATEGY: "recursive"
  GIT_CHECKOUT: "true"

before_script:
    - rustup update
    - rustup component add rust-src
    - cargo install cargo-config xargo
    - pushd bootloader-efi
    - rustup update
    - rustup component add rust-src

img:
    script:
     - |
        mkdir -p "$HOME/.rustup/toolchains/nightly-2017-11-29-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin" &&
        popd &&
        make ci-img IMG_TAG=$CI_COMMIT_REF_NAME
    artifacts:
        paths:
         - build/img/
        expire_in: 1 week
