# This is the CI configuration file

# General settings
[general]
# Do not prompt if settings are not defined
prompt = false

# Package settings
[packages]
acid = {}
autoconf = {}
automake = {}
#bash = {} # sh_xmalloc
binutils = {}
ca-certificates = {}
#cargo = {}
cleye = {}
#cmatrix = {} # ncurses
contain = {}
coreutils = {}
curl = {}
dash = {}
#diffutils = {} # sigaction issues
dosbox = {}
drivers = {}
#drivers-041 = {}
#duktape = {} # strptime
eduke32 = {}
exampled = {}
expat = {}
extrautils = {}
#fd = {} #  ctrlc-3.1.1
ffmpeg = {}
findutils = {}
freedoom = {}
freetype = {}
#friar = {} # mio patch
game-2048 = {}
games = {}
#gawk = {} # langinfo.h
gcc = {}
generaluser-gs = {}
#gigalomania = {}
git = {}
gnu-binutils = {}
gnu-grep = {}
gnu-make = {}
init = {}
installer = {}
ion = {}
ipcd = {}
jansson = {}
keyboard-sfx = {}
lci = {}
libiconv = {}
libjpeg = {}
liborbital = {}
libpng = {}
libsodium = {}
logd = {}
#lua = {} # tmpnam
#mdp = {} # ncursesw
#miniserve = {} # actix
nasm = {}
#ncdu = {} # ncurses
#ncurses = {} # mkstemp configure hang
#ncursesw = {} # mkstemp configure hang
netdb = {}
netstack = {}
netsurf = {}
netutils = {}
#newlib = {} # obsolete
#newlibtest = {} # obsolete
nulld = {}
openjazz = {}
openssl = {}
openttd = {}
openttd-opengfx = {}
openttd-openmsx = {}
orbdata = {}
orbital = {}
orbterm = {}
orbutils = {}
pastel = {}
patch = {}
periodictable = {}
#perl = {} # ctermid, tempnam, ttyname
pixelcannon = {}
pkgutils = {}
powerline = {}
prboom = {}
ptyd = {}
#python = {} # getaddrinfo
randd = {}
#readline = {} # ncurses
redoxfs = {}
#redox-ssh = {}
relibc = {}
ripgrep = {}
rs-nes = {}
#rust = {}
rust64 = {}
rustual-boy = {}
scummvm = {}
sdl = {}
sdl_image = {}
sdl_mixer = {}
sed = {}
shellstorm = {}
smith = {}
sodium = {}
sopwith = {}
#ssh = {}
terminfo = {}
termplay = {}
timidity = {}
ttf-hack = {}
userutils = {}
uutils = {}
#vim = {} # ncurses
#vttest = {} # fpathconf
xz = {}
zerod = {}
zlib = {}
