# This is the default configuration file

# General settings
[general]
# Do not prompt if settings are not defined
prompt = false

# Package settings
[packages]
#acid = {}
#autoconf = {}
#automake = {}
#bash = {}
#binutils = {}
#ca-certificates = {}
#cargo = {}
#cleye = {}
#contain = {}
coreutils = {}
#curl = {}
dash = {}
#diffutils = {}
#drivers = {}
extrautils = {}
#fd = {}
findutils = {}
#game-2048 = {}
#games = {}
#gawk = {}
#gcc = {}
#git = {}
#gnu-binutils = {}
#gnu-make = {}
#installer = {}
#ion = {}
#logd = {}
lua = {}
#nasm = {}
#netdb = {}
#netstack = {}
#netsurf = {}
#netutils = {}
#newlib = {}
nulld = {}
#openssl = {}
#orbdata = {}
#orbital = {}
#orbterm = {}
#orbutils = {}
#pastel = {}
#patch = {}
#pixelcannon = {}
#pkgutils = {}
#prboom = {}
ptyd = {}
#python = {}
randd = {}
#redoxfs = {}
#rs-nes = {}
#rust = {}
#rust64 = {}
#rustual-boy = {}
#sed = {}
#smith = {}
#sodium = {}
#termplay = {}
userutils = {}
uutils = {}
#xz = {}
zerod = {}

# User settings
[users.root]
# Password is set to "password"
password = "$argon2i$m=4096,t=10,p=1$Tnc4UVV0N00$ML9LIOujd3nmAfkAwEcSTMPqakWUF0OUiLWrIy0nGLk"
uid = 0
gid = 0
name = "root"
home = "/root"
shell = "/bin/lua"

[users.user]
# Password is unset
password = ""
shell = "/bin/lua"

[[files]]
path = "/etc/init.d/00_base"
data = """
nulld
zerod
randd
ptyd
pcid /etc/pcid/filesystem.toml
"""

[[files]]
path = "/etc/init.d/10_console"
data = """
getty display:2/activate
"""

[[files]]
path = "/etc/group"
data = """
root;0;root
user;1000;user
sudo;1;user
"""

[[files]]
path = "/etc/hostname"
data = """
redox
"""

[[files]]
path = "/etc/issue"
data = """
#### redoX XTREME Edition ####
# Login with the following:  #
# `user`                     #
# `root`:`password`          #
##############################

"""

[[files]]
path = "/etc/motd"
data = """

¡redoX XTREME Edition!

"""

[[files]]
path = "/usr/bin"
data = "/bin"
symlink = true
