# This is the default configuration file

# General settings
[general]
# Do not prompt if settings are not defined
prompt = false

# Package settings
[packages]
#drivers = {}
init = {}
nulld = {}
#pciids = {}
ramfs = {}
randd = {}
redoxfs = {}
zerod = {}

[[files]]
path="/etc/init.rc"
data="""
export PATH /bin
export TMPDIR /tmp
stdio debug:
echo Post stdio!
nulld
echo Post nulld!
zerod
echo Post zerod!
randd
echo Post randd!
# vesad T T G
# ps2d us
ramfs logging
echo Post ramfs!
# pcid /etc/pcid/initfs.toml
redoxfs --uuid $REDOXFS_UUID file $REDOXFS_BLOCK
echo Post redoxfs!
cd file:
export PATH file:/bin
run.d /etc/init.d
"""
